#ifndef ___STDAFX_H_
#define ___STDAFX_H_

#include <stdio.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <time.h>
#include <signal.h>
#include <net/if.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/can.h>
#include <linux/can/raw.h>
#include <stdio.h>
#include <stdarg.h>
#include <time.h>
#include <string.h>
#include <pthread.h>
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <signal.h>
#include <string.h>
#include <time.h>
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <ifaddrs.h>
#include <netinet/in.h>
#include <string.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <unistd.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <unistd.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <malloc.h>
#include <time.h>
#include <net/if.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <linux/can.h>
#include <linux/can/raw.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <termios.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <sys/wait.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "ajax.h"
#include "config.h"
#include "error.h"
#include "log.h"
#include "blueprint.h"
#include "charge.h"
#include "Hachiko.h"
#include "../thirdpart/mongoose/mongoose.h"
#include "config.h"
#include "log.h"
#include "error.h"
#include "Hachiko.h"
#include "charge.h"
#include "ajax.h"
#include "../thirdpart/sqlite/sqlite3.h"
#include "charge.h"
#include "blueprint.h"
#include "Hachiko.h"
#include "bms.h"
#include "config.h"
#include "log.h"
#include "error.h"
#include "charge.h"
#include "bms.h"
#include "config.h"
#include "log.h"
#include "error.h"
#include "config.h"
#include "error.h"
#include "log.h"
#include "ajax.h"
#include "Hachiko.h"
#include "log.h"
#include "config.h"
#include "error.h"
#include "log.h"
#include "config.h"
#include "charge.h"
#include "../thirdpart/mongoose/mongoose.h"
#include "../thirdpart/D8/librf.h"
#include "../thirdpart/sqlite/sqlite3.h"
#include "../thirdpart/extso/exso.h"
#include "list.h"
#include "ajax.h"
#include "config.h"
#include "error.h"
#include "log.h"
#include "Hachiko.h"
#include "charge.h"

#endif// ___STDAFX_H_
