#############################################################################
# Makefile for building: onbrowser
# Generated by qmake (2.01a) (Qt 4.8.2) on: Wed Aug 13 09:09:11 2014
# Project:  onbrowser.pro
# Template: app
# Command: /home/tom/workspace/qt-4.8.2-arm/bin/qmake -o Makefile onbrowser.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-arago-linux-gnueabi-gcc -lts
CXX           = arm-arago-linux-gnueabi-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qt-4.8.2-arm/mkspecs/qws/linux-arm-g++ -I. -I../qt-4.8.2-arm/include/QtCore -I../qt-4.8.2-arm/include/QtNetwork -I../qt-4.8.2-arm/include/QtWebKit -I../qt-4.8.2-arm/include/QtGui -I../qt-4.8.2/include -I../qt-4.8.2-arm/include -I. -Icopy -I.
LINK          = arm-arago-linux-gnueabi-g++ -lts
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/home/tom/workspace/qt-4.8.2-arm/lib -lQtGui -L/home/tom/workspace/tslib/lib -L/home/tom/workspace/qt-4.8.2-arm/lib -lQtNetwork -lQtCore -lQtWebKit -lpthread
AR            = arm-arago-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /home/tom/workspace/qt-4.8.2-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-arago-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = browser.cpp \
		browserwindow.cpp moc_browserwindow.cpp
OBJECTS       = browser.o \
		browserwindow.o \
		moc_browserwindow.o
DIST          = ../qt-4.8.2-arm/mkspecs/common/unix.conf \
		../qt-4.8.2-arm/mkspecs/common/linux.conf \
		../qt-4.8.2-arm/mkspecs/common/gcc-base.conf \
		../qt-4.8.2-arm/mkspecs/common/gcc-base-unix.conf \
		../qt-4.8.2-arm/mkspecs/common/g++-base.conf \
		../qt-4.8.2-arm/mkspecs/common/g++-unix.conf \
		../qt-4.8.2-arm/mkspecs/common/qws.conf \
		../qt-4.8.2-arm/mkspecs/qconfig.pri \
		../qt-4.8.2-arm/mkspecs/modules/qt_webkit_version.pri \
		../qt-4.8.2-arm/mkspecs/features/qt_functions.prf \
		../qt-4.8.2-arm/mkspecs/features/qt_config.prf \
		../qt-4.8.2-arm/mkspecs/features/exclusive_builds.prf \
		../qt-4.8.2-arm/mkspecs/features/default_pre.prf \
		../qt-4.8.2-arm/mkspecs/features/release.prf \
		../qt-4.8.2-arm/mkspecs/features/default_post.prf \
		../qt-4.8.2-arm/mkspecs/features/warn_on.prf \
		../qt-4.8.2-arm/mkspecs/features/qt.prf \
		../qt-4.8.2-arm/mkspecs/features/unix/thread.prf \
		../qt-4.8.2-arm/mkspecs/features/moc.prf \
		../qt-4.8.2-arm/mkspecs/features/resources.prf \
		../qt-4.8.2-arm/mkspecs/features/uic.prf \
		../qt-4.8.2-arm/mkspecs/features/yacc.prf \
		../qt-4.8.2-arm/mkspecs/features/lex.prf \
		../qt-4.8.2-arm/mkspecs/features/include_source_dir.prf \
		onbrowser.pro
QMAKE_TARGET  = browser
DESTDIR       = 
TARGET        = browser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: onbrowser.pro  ../qt-4.8.2-arm/mkspecs/qws/linux-arm-g++/qmake.conf ../qt-4.8.2-arm/mkspecs/common/unix.conf \
		../qt-4.8.2-arm/mkspecs/common/linux.conf \
		../qt-4.8.2-arm/mkspecs/common/gcc-base.conf \
		../qt-4.8.2-arm/mkspecs/common/gcc-base-unix.conf \
		../qt-4.8.2-arm/mkspecs/common/g++-base.conf \
		../qt-4.8.2-arm/mkspecs/common/g++-unix.conf \
		../qt-4.8.2-arm/mkspecs/common/qws.conf \
		../qt-4.8.2-arm/mkspecs/qconfig.pri \
		../qt-4.8.2-arm/mkspecs/modules/qt_webkit_version.pri \
		../qt-4.8.2-arm/mkspecs/features/qt_functions.prf \
		../qt-4.8.2-arm/mkspecs/features/qt_config.prf \
		../qt-4.8.2-arm/mkspecs/features/exclusive_builds.prf \
		../qt-4.8.2-arm/mkspecs/features/default_pre.prf \
		../qt-4.8.2-arm/mkspecs/features/release.prf \
		../qt-4.8.2-arm/mkspecs/features/default_post.prf \
		../qt-4.8.2-arm/mkspecs/features/warn_on.prf \
		../qt-4.8.2-arm/mkspecs/features/qt.prf \
		../qt-4.8.2-arm/mkspecs/features/unix/thread.prf \
		../qt-4.8.2-arm/mkspecs/features/moc.prf \
		../qt-4.8.2-arm/mkspecs/features/resources.prf \
		../qt-4.8.2-arm/mkspecs/features/uic.prf \
		../qt-4.8.2-arm/mkspecs/features/yacc.prf \
		../qt-4.8.2-arm/mkspecs/features/lex.prf \
		../qt-4.8.2-arm/mkspecs/features/include_source_dir.prf \
		/home/tom/workspace/qt-4.8.2-arm/lib/libQtGui.prl \
		/home/tom/workspace/qt-4.8.2-arm/lib/libQtNetwork.prl \
		/home/tom/workspace/qt-4.8.2-arm/lib/libQtCore.prl
	$(QMAKE) -o Makefile onbrowser.pro
../qt-4.8.2-arm/mkspecs/common/unix.conf:
../qt-4.8.2-arm/mkspecs/common/linux.conf:
../qt-4.8.2-arm/mkspecs/common/gcc-base.conf:
../qt-4.8.2-arm/mkspecs/common/gcc-base-unix.conf:
../qt-4.8.2-arm/mkspecs/common/g++-base.conf:
../qt-4.8.2-arm/mkspecs/common/g++-unix.conf:
../qt-4.8.2-arm/mkspecs/common/qws.conf:
../qt-4.8.2-arm/mkspecs/qconfig.pri:
../qt-4.8.2-arm/mkspecs/modules/qt_webkit_version.pri:
../qt-4.8.2-arm/mkspecs/features/qt_functions.prf:
../qt-4.8.2-arm/mkspecs/features/qt_config.prf:
../qt-4.8.2-arm/mkspecs/features/exclusive_builds.prf:
../qt-4.8.2-arm/mkspecs/features/default_pre.prf:
../qt-4.8.2-arm/mkspecs/features/release.prf:
../qt-4.8.2-arm/mkspecs/features/default_post.prf:
../qt-4.8.2-arm/mkspecs/features/warn_on.prf:
../qt-4.8.2-arm/mkspecs/features/qt.prf:
../qt-4.8.2-arm/mkspecs/features/unix/thread.prf:
../qt-4.8.2-arm/mkspecs/features/moc.prf:
../qt-4.8.2-arm/mkspecs/features/resources.prf:
../qt-4.8.2-arm/mkspecs/features/uic.prf:
../qt-4.8.2-arm/mkspecs/features/yacc.prf:
../qt-4.8.2-arm/mkspecs/features/lex.prf:
../qt-4.8.2-arm/mkspecs/features/include_source_dir.prf:
/home/tom/workspace/qt-4.8.2-arm/lib/libQtGui.prl:
/home/tom/workspace/qt-4.8.2-arm/lib/libQtNetwork.prl:
/home/tom/workspace/qt-4.8.2-arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile onbrowser.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/onbrowser1.0.0 || $(MKDIR) .tmp/onbrowser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/onbrowser1.0.0/ && $(COPY_FILE) --parents browserwindow.h .tmp/onbrowser1.0.0/ && $(COPY_FILE) --parents browser.cpp browserwindow.cpp .tmp/onbrowser1.0.0/ && (cd `dirname .tmp/onbrowser1.0.0` && $(TAR) onbrowser1.0.0.tar onbrowser1.0.0 && $(COMPRESS) onbrowser1.0.0.tar) && $(MOVE) `dirname .tmp/onbrowser1.0.0`/onbrowser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/onbrowser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_browserwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_browserwindow.cpp
moc_browserwindow.cpp: browserwindow.h
	/home/tom/workspace/qt-4.8.2-arm/bin/moc $(DEFINES) $(INCPATH) browserwindow.h -o moc_browserwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

browser.o: browser.cpp browserwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browser.o browser.cpp

browserwindow.o: browserwindow.cpp browserwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browserwindow.o browserwindow.cpp

moc_browserwindow.o: moc_browserwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_browserwindow.o moc_browserwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

