; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\main.o --depend=..\Output\main.d --cpu=Cortex-M3 --apcs=interwork -O1 -I.\src -I.\inc -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_CL --omf_browse=..\Output\main.crf src\main.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

main PROC
        BL       ADSample_Init
        BL       UART_Init
        BL       LED_IOinit
        BL       Relay_IOinit
        BL       Coupler_IOinit
        BL       Timer_Init
        BL       Watchdog_Init
        BL       Flash_Init
        MOVS     r3,#2
        MOVS     r2,#0x4e
        LDR      r1,|L1.216|
        LDR      r0,|L1.220|
        BL       Cal_Init
        CPSIE    i
        LDR      r5,|L1.220|
        LDR      r8,|L1.224|
        LDR      r9,|L1.228|
        LDR      r4,|L1.232|
        LDR      r10,|L1.236|
        LDR      r6,|L1.240|
        MOV      r7,#0xaaaa
        SUBS     r5,r5,#0x10
|L1.70|
        STR      r7,[r8,#0]
        LDRB     r0,[r9,#0]  ; Systimememb
        LSLS     r0,r0,#31
        BNE      |L1.130|
        LDRB     r0,[r5,#1]  ; Samp_ADdata_Stream
        LDR      r1,|L1.220|
        ADD      r0,r4,r0,LSL #4
        SUBS     r1,r1,#0x10
        LDR      r2,[r0,#0xc]
        LDR      r0,|L1.244|
        BLX      r2
        LDRH     r0,[r5,#0x12]  ; Samp_ADdata_Stream
        CBZ      r0,|L1.112|
        LDR      r0,|L1.220|
        SUBS     r0,r0,#0x10
        BL       Cal_ADscream_Change
        CBZ      r0,|L1.164|
|L1.112|
        LDR      r1,|L1.220|
        LDR      r0,|L1.244|
        SUBS     r1,r1,#0x10
        BL       ADSample_Scream_Col
|L1.122|
        LDR      r0,|L1.220|
        SUBS     r0,r0,#0x10
        BL       ADSample_Change
|L1.130|
        LDR      r0,|L1.244|
        BL       Coupler_Updata
        LDR      r1,|L1.220|
        LDR      r0,|L1.244|
        SUBS     r1,r1,#0x10
        BL       Relay_Control
        LDRB     r0,[r10,#0]  ; U1_RXfin
        LDRB     r1,[r6,#0]  ; U1_TXfin
        MVNS     r0,r0
        LSLS     r0,r0,#30
        ORRS     r0,r0,r1,LSL #31
        BEQ      |L1.182|
        B        |L1.194|
|L1.164|
        LDRB     r0,[r5,#1]  ; Samp_ADdata_Stream
        LDR      r1,|L1.220|
        ADD      r0,r4,r0,LSL #4
        SUBS     r1,r1,#0x10
        LDRB     r0,[r0,#0xa]
        BL       Cal_ADdata_Copy
        B        |L1.122|
|L1.182|
        LDR      r2,|L1.220|
        LDR      r1,|L1.248|
        SUBS     r2,r2,#0x10
        LDR      r0,|L1.252|
        BL       DATA_RecProc
|L1.194|
        LDRB     r0,[r6,#0]  ; U1_TXfin
        AND      r0,r0,#0xd
        CMP      r0,#9
        BNE      |L1.70|
        LDR      r2,|L1.244|
        LDR      r1,|L1.248|
        LDR      r0,|L1.252|
        BL       DATA_TraProc
        B        |L1.70|
        ENDP

|L1.216|
        DCD      0x0801f800
|L1.220|
        DCD      Samp_ADdata_Stream+0x10
|L1.224|
        DCD      0x40003000
|L1.228|
        DCD      Systimememb
|L1.232|
        DCD      Samp_DataArr
|L1.236|
        DCD      U1_RXfin
|L1.240|
        DCD      U1_TXfin
|L1.244|
        DCD      Samp_DataStat
|L1.248|
        DCD      U1_RxTxLen
|L1.252|
        DCD      U1_FIFOBuff

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT main [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ADSample_Init [CODE]
        IMPORT UART_Init [CODE]
        IMPORT LED_IOinit [CODE]
        IMPORT Relay_IOinit [CODE]
        IMPORT Coupler_IOinit [CODE]
        IMPORT Timer_Init [CODE]
        IMPORT Watchdog_Init [CODE]
        IMPORT Flash_Init [CODE]
        IMPORT Cal_Init [CODE]
        IMPORT Cal_ADscream_Change [CODE]
        IMPORT Cal_ADdata_Copy [CODE]
        IMPORT ADSample_Scream_Col [CODE]
        IMPORT ADSample_Change [CODE]
        IMPORT Coupler_Updata [CODE]
        IMPORT Relay_Control [CODE]
        IMPORT DATA_RecProc [CODE]
        IMPORT DATA_TraProc [CODE]
        IMPORT Samp_ADdata_Stream [DATA]
        IMPORT Systimememb [DATA]
        IMPORT Samp_DataArr [DATA]
        IMPORT U1_RXfin [DATA]
        IMPORT U1_TXfin [DATA]
        IMPORT Samp_DataStat [DATA]
        IMPORT U1_RxTxLen [DATA]
        IMPORT U1_FIFOBuff [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
