; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\sys_init.o --depend=..\Output\sys_init.d --cpu=Cortex-M3 --apcs=interwork -O1 -I.\src -I.\inc -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_CL --omf_browse=..\Output\sys_init.crf src\SYS_Init.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

System_Myinit PROC
        LDR      r0,|L1.292|
        LDR      r1,[r0,#0]
        ORR      r1,r1,#1
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        LDR      r2,|L1.296|
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        BIC      r1,r1,#0x40000
        STR      r1,[r0,#0]
        MOV      r1,#0x9f0000
        STR      r1,[r0,#8]
        LDR      r1,[r0,#4]
        LDR      r2,|L1.300|
        ANDS     r1,r1,r2
        STR      r1,[r0,#4]
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x1d0000
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x10000
        STR      r1,[r0,#0]
|L1.56|
        LDR      r1,[r0,#0]
        LSLS     r1,r1,#14
        BPL      |L1.56|
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x400
        STR      r1,[r0,#4]
        LDR      r1,|L1.304|
        LDR      r2,[r1,#0]
        BIC      r2,r2,#0xf
        STR      r2,[r1,#0]
        LDR      r2,[r1,#0]
        ORR      r2,r2,#0x10
        STR      r2,[r1,#0]
        LDR      r2,[r1,#0]
        ORR      r2,r2,#2
        STR      r2,[r1,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x1000000
        STR      r1,[r0,#0]
|L1.104|
        LDR      r1,[r0,#0]
        LSLS     r1,r1,#6
        BPL      |L1.104|
        LDR      r1,[r0,#4]
        ORR      r1,r1,#2
        STR      r1,[r0,#4]
|L1.118|
        LDR      r1,[r0,#4]
        LSLS     r1,r1,#31
        BNE      |L1.118|
        LDR      r1,[r0,#0]
        BIC      r1,r1,#1
        STR      r1,[r0,#0]
        BX       lr
        ENDP

NVIC_Myinit PROC
        LDR      r1,|L1.308|
        MOVS     r0,#0x70
        STRB     r0,[r1,#0]
        LDR      r1,|L1.308|
        MOVS     r0,#0x60
        SUBS     r1,r1,#8
        STRB     r0,[r1,#0]
        MOVS     r0,#0x40
        SUBS     r1,r1,#1
        STRB     r0,[r1,#0]
        SUBS     r1,r1,#7
        STRB     r0,[r1,#0]
        SUBS     r1,r1,#1
        STRB     r0,[r1,#0]
        LDR      r2,|L1.308|
        MOVS     r1,#0x50
        SUBS     r2,r2,#0x12
        STRB     r1,[r2,#0]
        LDR      r2,|L1.308|
        ADDS     r2,r2,#0x1c
        STRB     r0,[r2,#0]
        SUBS     r2,r2,#1
        STRB     r0,[r2,#0]
        SUBS     r0,r2,#1
        STRB     r1,[r0,#0]
        LDR      r1,|L1.308|
        MOVS     r0,#0x20
        SUBS     r1,r1,#2
        STRB     r0,[r1,#0]
        LDR      r1,|L1.308|
        MOVS     r0,#0
        SUBS     r1,r1,#0xc
        STRB     r0,[r1,#0]
        LDR      r0,|L1.312|
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x20
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x20000000
        STR      r1,[r0,#0]
        LDR      r1,[r0,#4]
        ORR      r1,r1,#8
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x10000000
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x200000
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x100000
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x80000
        STR      r1,[r0,#0]
        LDR      r1,[r0,#8]
        ORR      r1,r1,#2
        STR      r1,[r0,#8]
        LDR      r1,[r0,#8]
        ORR      r1,r1,#1
        STR      r1,[r0,#8]
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x80000000
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x2000000
        STR      r1,[r0,#0]
        BX       lr
        ENDP

|L1.292|
        DCD      0x40021000
|L1.296|
        DCD      0xfef6ffff
|L1.300|
        DCD      0xff80c00c
|L1.304|
        DCD      0x40022000
|L1.308|
        DCD      0xe000e425
|L1.312|
        DCD      0xe000e100

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "src\\SYS_Init.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |System_Reset|
#line 82
|System_Reset| PROC
#line 83

 CPSID f  
 LDR R0, =0x05FA0004
 LDR R1, =0xE000ED0C
 STR R0, [R1]  
 NOP
 B .  
	ENDP

;*** End   embedded assembler ***

        EXPORT System_Myinit [CODE]
        EXPORT NVIC_Myinit [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
