; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\watchdog.o --depend=..\Output\watchdog.d --cpu=Cortex-M3 --apcs=interwork -O1 -I.\src -I.\inc -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_CL --omf_browse=..\Output\watchdog.crf src\Watchdog.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

Watchdog_Init PROC
        LDR      r0,|L1.80|
        LDR      r1,[r0,#0x24]
        ORR      r1,r1,#1
        STR      r1,[r0,#0x24]
|L1.10|
        LDR      r1,[r0,#0x24]
        LSLS     r1,r1,#30
        BPL      |L1.10|
        LDR      r0,|L1.84|
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x100
        STR      r1,[r0,#4]
        LDR      r0,|L1.88|
        MOV      r2,#0xaaaa
        STR      r2,[r0,#0]
        ASRS     r1,r2,#1
        STR      r1,[r0,#0]
|L1.38|
        LDR      r1,[r0,#0xc]
        LSLS     r1,r1,#31
        BNE      |L1.38|
        MOVS     r1,#3
        STR      r1,[r0,#4]
|L1.48|
        LDR      r1,[r0,#0xc]
        LSLS     r1,r1,#30
        BMI      |L1.48|
        MOV      r1,#0xfff
        STR      r1,[r0,#8]
        LDR      r1,|L1.92|
        LDR      r1,[r1,#0x1c]
        LSLS     r1,r1,#29
        BPL      |L1.76|
        MOV      r1,#0xcccc
        STR      r1,[r0,#0]
        BX       lr
|L1.76|
        STR      r2,[r0,#0]
        BX       lr
        ENDP

|L1.80|
        DCD      0x40021000
|L1.84|
        DCD      0xe0042000
|L1.88|
        DCD      0x40003000
|L1.92|
        DCD      0x40022000

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT Watchdog_Init [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
