######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 18 09:29:25 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mongoose.h tom.h
SOURCES += mongoose.c tom.c
