######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 13 09:09:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += browserwindow.h
SOURCES += browser.cpp browserwindow.cpp
