; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\stat_control.o --depend=..\Output\stat_control.d --cpu=Cortex-M3 --apcs=interwork -O1 -I.\src -I.\inc -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_CL --omf_browse=..\Output\stat_control.crf src\Stat_control.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

IOMemb_Write PROC
        PUSH     {r4,lr}
        LDR      r4,|L1.924|
        LDRB     r2,[r4,r0,LSL #1]
        CMP      r2,#0xff
        BEQ      |L1.40|
        CMP      r0,#0xff
        BEQ      |L1.40|
        LDR      r3,|L1.928|
        ORR      r3,r3,r2,LSL #8
        ADD      r0,r4,r0,LSL #1
        MOVS     r2,#1
        LDRB     r0,[r0,#1]
        LSLS     r2,r2,r0
        CBZ      r1,|L1.42|
        MOVS     r0,#0
|L1.36|
        LSLS     r2,r2,r0
        STR      r2,[r3,#0x10]
|L1.40|
        POP      {r4,pc}
|L1.42|
        MOVS     r0,#0x10
        B        |L1.36|
        ENDP

IOMemb_Read PROC
        PUSH     {r4,lr}
        LDR      r3,|L1.924|
        ADD      r2,r3,r0,LSL #1
        LDRB     r4,[r2,#1]
        MOVS     r2,#1
        LSLS     r2,r2,r4
        LDRB     r0,[r3,r0,LSL #1]
        LDR      r3,|L1.928|
        ORR      r0,r3,r0,LSL #8
        CMP      r1,#1
        BEQ      |L1.78|
        MOVS     r0,#0
        POP      {r4,pc}
|L1.78|
        LDR      r0,[r0,#0xc]
        TST      r0,r2
        BEQ      |L1.88|
        MOVS     r0,#1
        POP      {r4,pc}
|L1.88|
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP

LED_IOinit PROC
        LDR      r0,|L1.932|
        LDR      r1,[r0,#0x18]
        ORR      r1,r1,#0x10
        STR      r1,[r0,#0x18]
        LDR      r0,|L1.936|
        LDR      r1,[r0,#4]
        BIC      r1,r1,#0x3300000
        STR      r1,[r0,#4]
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x2200000
        STR      r1,[r0,#4]
        LDR      r1,[r0,#4]
        BIC      r1,r1,#0xcc00000
        STR      r1,[r0,#4]
        LDR      r1,[r0,#4]
        ORR      r1,r1,#0x4400000
        STR      r1,[r0,#4]
        BX       lr
        ENDP

Relay_IOinit PROC
        LDR      r0,|L1.932|
        LDR      r1,[r0,#0x18]
        ORR      r1,r1,#0x14
        STR      r1,[r0,#0x18]
        LDR      r0,|L1.936|
        LDR      r1,[r0,#0]
        LDR      r2,|L1.940|
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        LDR      r2,|L1.944|
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        LDR      r2,|L1.948|
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r0,|L1.952|
        LDR      r1,[r0,#0]
        MOV      r2,#0x3333
        BICS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        MOV      r2,#0x2222
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        MOV      r2,#0xcccc
        BICS     r1,r1,r2
        STR      r1,[r0,#0]
        BX       lr
        ENDP

Coupler_IOinit PROC
        LDR      r0,|L1.932|
        LDR      r1,[r0,#0x18]
        ORR      r1,r1,#8
        STR      r1,[r0,#0x18]
        LDR      r0,|L1.956|
        LDR      r1,[r0,#0]
        LDR      r2,|L1.960|
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        ROR      r2,r2,#30
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        LDR      r2,|L1.964|
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        ADDS     r0,r0,#4
        LDR      r1,[r0,#0]
        LDR      r2,|L1.968|
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        ROR      r2,r2,#30
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        LDR      r2,|L1.972|
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        BX       lr
        ENDP

OutputCmd_DataPro PROC
        LDRH     r2,[r0,#0]
        LDRH     r0,[r0,#2]
        CMP      r2,r0
        BNE      |L1.296|
        LSLS     r0,r2,#8
        ORR      r0,r0,r2,LSR #8
        STRH     r0,[r1,#2]
        MOVS     r0,#0
        BX       lr
|L1.296|
        LDR      r2,|L1.924|
        SUBS     r2,r2,#0x11
        LDRB     r0,[r2,#0]  ; errornum
        ADDS     r3,r0,#1
        STRB     r3,[r2,#0]
        CMP      r0,#5
        BLS      |L1.318|
        MOVS     r0,#0
        STRH     r0,[r1,#2]
        MOVS     r0,#1
        BX       lr
|L1.318|
        MOVS     r0,#1
        BX       lr
        ENDP

IOMemb_DataPro PROC
        PUSH     {r4,lr}
        MOVS     r1,#0
        LDR      r3,|L1.924|
        SUBS     r3,r3,#0x10
|L1.330|
        LDRB     r2,[r0,r1]
        CMP      r2,#0x10
        BCS      |L1.340|
        ADDS     r4,r3,r1
        STRB     r2,[r4,#1]
|L1.340|
        ADDS     r2,r0,r1
        LDRB     r2,[r2,#1]
        CMP      r2,#0x10
        BCS      |L1.350|
        STRB     r2,[r3,r1]
|L1.350|
        ADDS     r1,r1,#2
        UXTB     r1,r1
        CMP      r1,#0x10
        BCC      |L1.330|
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP

Coupler_Updata PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        LDR      r0,|L1.956|
        ADDS     r0,r0,#8
        LDR      r1,[r0,#0]
        LDR      r2,[r0,#0]
        UBFX     r1,r1,#1,#1
        UBFX     r2,r2,#11,#1
        ORR      r1,r1,r2,LSL #4
        LDR      r2,[r0,#0]
        UBFX     r2,r2,#13,#1
        ORR      r1,r1,r2,LSL #5
        LDR      r2,[r0,#0]
        UBFX     r2,r2,#15,#1
        ORR      r1,r1,r2,LSL #6
        MVNS     r1,r1
        AND      r1,r1,#0x71
        STRB     r1,[r4,#0x22]!
        LDR      r0,[r0,#0]
        LDRB     r1,[r4,#2]
        ORR      r1,r1,#1
        UBFX     r0,r0,#14,#1
        BICS     r1,r1,r0
        STRB     r1,[r4,#2]
        LDR      r5,|L1.924|
        MOVS     r1,#1
        SUBS     r5,r5,#0x10
        LDRB     r0,[r5,#1]  ; OutSetNumArr
        BL       IOMemb_Read
        LSLS     r6,r0,#4
        LDRB     r0,[r5,#0]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Read
        LDRB     r1,[r4,#2]
        ORR      r0,r6,r0,LSL #7
        AND      r1,r1,#0x67
        ORRS     r0,r0,r1
        ORR      r0,r0,#8
        STRB     r0,[r4,#2]
        LDRB     r0,[r5,#4]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Read
        LDRB     r1,[r4,#3]
        AND      r1,r1,#0xf6
        ORR      r6,r0,r1
        LDRB     r0,[r5,#3]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Read
        ORR      r0,r6,r0,LSL #3
        STRB     r0,[r4,#3]
        POP      {r4-r6,pc}
        ENDP

Relay_Control PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r7,r1
        LDRH     r4,[r7,#2]
        LDR      r6,|L1.924|
        LDRH     r0,[r7,#4]
        SUBS     r6,r6,#0x10
        CBZ      r0,|L1.544|
        LDRB     r0,[r6,#1]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
        LDRB     r0,[r6,#4]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
        MOV      r4,#0x100
|L1.544|
        LDRB     r0,[r5,#0x22]
        CBNZ     r0,|L1.562|
        LDRB     r1,[r5,#0x1d]
        CBNZ     r1,|L1.562|
        LDRB     r1,[r5,#0x1e]
        CBNZ     r1,|L1.562|
        LDRB     r1,[r5,#0x1f]
        CBZ      r1,|L1.682|
|L1.562|
        TST      r0,#0x63
        BEQ      |L1.596|
        LDRB     r0,[r6,#1]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
        LDRB     r0,[r6,#4]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
        MOV      r0,#0x1db
        ANDS     r4,r4,r0
        LDRH     r1,[r7,#2]
        ANDS     r1,r1,r0
        STRH     r1,[r7,#2]
|L1.596|
        LDRB     r0,[r5,#0x22]
        LSLS     r0,r0,#29
        BMI      |L1.618|
        LDRB     r0,[r5,#0x1d]
        LSLS     r0,r0,#29
        BNE      |L1.618|
        LDRB     r0,[r5,#0x1e]
        BICS     r0,r0,#0x20
        BEQ      |L1.638|
|L1.618|
        LDRB     r0,[r6,#1]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
        MOV      r0,#0x1fb
        ANDS     r4,r4,r0
        LDRH     r1,[r7,#2]
        ANDS     r1,r1,r0
        STRH     r1,[r7,#2]
|L1.638|
        LDRB     r0,[r5,#0x22]
        LSLS     r0,r0,#28
        BMI      |L1.662|
        LDRB     r0,[r5,#0x1d]
        TST      r0,#0x38
        BNE      |L1.662|
        LDRB     r0,[r5,#0x1f]
        BICS     r0,r0,#0x20
        BEQ      |L1.682|
|L1.662|
        LDRB     r0,[r6,#4]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
        MOV      r0,#0x1df
        ANDS     r4,r4,r0
        LDRH     r1,[r7,#2]
        ANDS     r1,r1,r0
        STRH     r1,[r7,#2]
|L1.682|
        LDRB     r0,[r5,#0x24]
        MVN      r0,r0,LSR #5
        LSLS     r0,r0,#30
        BEQ      |L1.700|
        MOV      r0,#0x1f3
        ANDS     r4,r4,r0
|L1.700|
        LDRB     r0,[r5,#0x25]
        MVN      r0,r0,LSR #1
        LSLS     r0,r0,#30
        BEQ      |L1.718|
        MOV      r0,#0x19f
        ANDS     r4,r4,r0
|L1.718|
        LSLS     r0,r4,#30
        BPL      |L1.732|
        LDRB     r0,[r6,#0]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.740|
|L1.732|
        LDRB     r0,[r6,#0]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.740|
        LSLS     r0,r4,#29
        BPL      |L1.754|
        LDRB     r0,[r6,#1]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.762|
|L1.754|
        LDRB     r0,[r6,#1]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.762|
        LSLS     r0,r4,#27
        BPL      |L1.776|
        LDRB     r0,[r6,#3]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.784|
|L1.776|
        LDRB     r0,[r6,#3]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.784|
        LSLS     r0,r4,#26
        BPL      |L1.798|
        LDRB     r0,[r6,#4]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.806|
|L1.798|
        LDRB     r0,[r6,#4]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.806|
        LSLS     r0,r4,#28
        BPL      |L1.820|
        LDRB     r0,[r6,#2]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.828|
|L1.820|
        LDRB     r0,[r6,#2]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.828|
        LSLS     r0,r4,#25
        BPL      |L1.842|
        LDRB     r0,[r6,#5]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.850|
|L1.842|
        LDRB     r0,[r6,#5]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.850|
        LSLS     r0,r4,#24
        BPL      |L1.864|
        LDRB     r0,[r6,#6]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.872|
|L1.864|
        LDRB     r0,[r6,#6]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.872|
        LSLS     r0,r4,#23
        BPL      |L1.886|
        LDRB     r0,[r6,#7]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.894|
|L1.886|
        LDRB     r0,[r6,#7]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.894|
        LSLS     r0,r4,#22
        BPL      |L1.908|
        LDRB     r0,[r6,#8]  ; OutSetNumArr
        MOVS     r1,#1
        BL       IOMemb_Write
        B        |L1.916|
|L1.908|
        LDRB     r0,[r6,#8]  ; OutSetNumArr
        MOVS     r1,#0
        BL       IOMemb_Write
|L1.916|
        MOVS     r0,#0
        POP      {r4-r8,pc}
        ENDP

        DCW      0x0000
|L1.924|
        DCD      ||.data||+0x11
|L1.928|
        DCD      0x40010000
|L1.932|
        DCD      0x40021000
|L1.936|
        DCD      0x40011000
|L1.940|
        DCD      0xffccccff
|L1.944|
        DCD      0x00222200
|L1.948|
        DCD      0xff3333ff
|L1.952|
        DCD      0x40010800
|L1.956|
        DCD      0x40010c00
|L1.960|
        DCD      0xcfffffcf
|L1.964|
        DCD      0x40000040
|L1.968|
        DCD      0xcccfcfcc
|L1.972|
        DCD      0x44404044

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=0

errornum
        DCB      0x00
OutSetNumArr
        DCB      0x05,0x03,0x07
        DCB      0x04,0x02,0x06,0x00
        DCB      0x01,0xff,0xff,0xff
        DCB      0xff,0xff,0xff,0xff
        DCB      0xff
OutMemb
        DCB      0x08,0x01,0x08
        DCB      0x02,0x08,0x03,0x10
        DCB      0x04,0x10,0x05,0x08
        DCB      0x00,0x10,0x02,0x10
        DCB      0x03,0xff,0xff,0xff
        DCB      0xff,0xff,0xff,0xff
        DCB      0xff,0xff,0xff,0xff
        DCB      0xff,0xff,0xff,0xff
        DCB      0xff

        EXPORT LED_IOinit [CODE]
        EXPORT Relay_IOinit [CODE]
        EXPORT Coupler_IOinit [CODE]
        EXPORT OutputCmd_DataPro [CODE]
        EXPORT IOMemb_DataPro [CODE]
        EXPORT Coupler_Updata [CODE]
        EXPORT Relay_Control [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP IOMemb_Write
        KEEP IOMemb_Read
        KEEP errornum
        KEEP OutSetNumArr
        KEEP OutMemb

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
