; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\flash.o --depend=..\Output\flash.d --cpu=Cortex-M3 --apcs=interwork -O1 -I.\src -I.\inc -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_CL --omf_browse=..\Output\flash.crf src\Flash.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

Flash_Init PROC
        LDR      r0,|L1.596|
        LDR      r1,[r0,#0]
        ORR      r1,r1,#1
        STR      r1,[r0,#0]
|L1.10|
        LDR      r1,[r0,#0]
        LSLS     r1,r1,#30
        BPL      |L1.10|
        BX       lr
        ENDP

Flash_FPEC_Unlock PROC
        LDR      r0,|L1.600|
        LDR      r1,[r0,#0x10]
        LSLS     r1,r1,#24
        BPL      |L1.44|
        LDR      r1,|L1.604|
        STR      r1,[r0,#4]
        LDR      r1,|L1.608|
        STR      r1,[r0,#4]
        LDR      r0,[r0,#0x10]
        LSLS     r0,r0,#24
        BPL      |L1.44|
        MOVS     r0,#1
        BX       lr
|L1.44|
        MOVS     r0,#0
        BX       lr
        ENDP

Flash_FPEC_Lock PROC
        LDR      r0,|L1.600|
        LDR      r1,[r0,#0x10]
        ORR      r1,r1,#0x80
        STR      r1,[r0,#0x10]
        BX       lr
        ENDP

Flash_OPT_Unlock PROC
        PUSH     {lr}
        BL       Flash_FPEC_Unlock
        CBNZ     r0,|L1.94|
        LDR      r0,|L1.600|
        LDR      r1,[r0,#0x10]
        LSLS     r1,r1,#22
        BMI      |L1.94|
        LDR      r1,|L1.604|
        STR      r1,[r0,#8]
        LDR      r1,|L1.608|
        STR      r1,[r0,#8]
        LDR      r0,[r0,#0x10]
        LSLS     r0,r0,#22
        BMI      |L1.94|
        MOVS     r0,#1
        POP      {pc}
|L1.94|
        MOVS     r0,#0
        POP      {pc}
        ENDP

Flash_OPT_Lock PROC
        PUSH     {lr}
        LDR      r2,|L1.600|
        LDR      r0,[r2,#0x10]
        LSLS     r0,r0,#22
        BPL      |L1.124|
        BL       Flash_FPEC_Unlock
        CMP      r0,#0
        BNE      |L1.124|
        LDR      r0,[r2,#0x10]
        BIC      r0,r0,#0x200
        STR      r0,[r2,#0x10]
|L1.124|
        POP      {pc}
        ENDP

Flash_Halfword_Program PROC
        LDR      r2,|L1.600|
        LDR      r3,[r2,#0xc]
        LSLS     r3,r3,#31
        BNE      |L1.202|
        SUB      r3,r0,#0x8000000
        CMP      r3,#0x20000
        BCS      |L1.202|
        LDR      r3,[r2,#0x10]
        BIC      r3,r3,#7
        STR      r3,[r2,#0x10]
        LDR      r3,[r2,#0x10]
        ORR      r3,r3,#1
        STR      r3,[r2,#0x10]
        STRH     r1,[r0,#0]
|L1.162|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.162|
        LDR      r0,[r2,#0xc]
        TST      r0,#0x14
        BEQ      |L1.184|
        MOVS     r0,#0x14
        STR      r0,[r2,#0xc]
        MOVS     r0,#1
        BX       lr
|L1.184|
        CMP      r1,r1
        BNE      |L1.202|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#26
        BPL      |L1.202|
        MOVS     r0,#0x20
        STR      r0,[r2,#0xc]
        MOVS     r0,#0
        BX       lr
|L1.202|
        MOVS     r0,#1
        BX       lr
        ENDP

Flash_Page_Erase PROC
        PUSH     {lr}
        MOV      r3,r0
        LDR      r2,|L1.600|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.224|
        BL       Flash_FPEC_Unlock
        CBZ      r0,|L1.228|
|L1.224|
        MOVS     r0,#1
        POP      {pc}
|L1.228|
        LDR      r0,[r2,#0x10]
        BIC      r0,r0,#7
        STR      r0,[r2,#0x10]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#2
        STR      r0,[r2,#0x10]
        STR      r3,[r2,#0x14]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#0x40
        STR      r0,[r2,#0x10]
|L1.254|
        LDR      r1,[r2,#0xc]
        LSLS     r1,r1,#31
        BNE      |L1.254|
        MOV      r1,#0x200
        LSRS     r0,r3,#11
        LSLS     r0,r0,#11
        B        |L1.284|
|L1.270|
        LDM      r0!,{r2}
        ADDS     r2,r2,#1
        BEQ      |L1.280|
        MOVS     r0,#1
        POP      {pc}
|L1.280|
        SUBS     r1,r1,#1
        UXTH     r1,r1
|L1.284|
        CMP      r1,#0
        BNE      |L1.270|
        MOVS     r0,#0
        POP      {pc}
        ENDP

Flash_Mass_Erase PROC
        PUSH     {lr}
        LDR      r2,|L1.600|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.338|
        BL       Flash_FPEC_Unlock
        CBNZ     r0,|L1.338|
        LDR      r0,[r2,#0x10]
        BIC      r0,r0,#7
        STR      r0,[r2,#0x10]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#4
        STR      r0,[r2,#0x10]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#0x40
        STR      r0,[r2,#0x10]
|L1.332|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.332|
|L1.338|
        MOVS     r0,#0
        POP      {pc}
        ENDP

Flash_OPTBYTE_Program PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOV      r3,r1
        LDR      r2,|L1.600|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.428|
        BL       Flash_OPT_Unlock
        CBNZ     r0,|L1.428|
        LDR      r0,|L1.612|
        ADD      r0,r0,r4
        CMP      r0,#0xf
        BHI      |L1.428|
        LDR      r0,[r2,#0x10]
        BIC      r0,r0,#0x30
        STR      r0,[r2,#0x10]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#0x10
        STR      r0,[r2,#0x10]
        STRH     r3,[r4,#0]
|L1.388|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.388|
        LDR      r0,[r2,#0xc]
        TST      r0,#0x14
        BEQ      |L1.410|
        MOVS     r0,#0x14
        STR      r0,[r2,#0xc]
        MOVS     r0,#1
        POP      {r4,pc}
|L1.410|
        CMP      r3,r3
        BNE      |L1.428|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#26
        BPL      |L1.428|
        MOVS     r0,#0x20
        STR      r0,[r2,#0xc]
        MOVS     r0,#0
        POP      {r4,pc}
|L1.428|
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP

Flash_OPTBYTE_Erase PROC
        PUSH     {lr}
        LDR      r2,|L1.600|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.478|
        BL       Flash_OPT_Unlock
        CBNZ     r0,|L1.478|
        LDR      r0,[r2,#0x10]
        BIC      r0,r0,#0x30
        STR      r0,[r2,#0x10]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#0x20
        STR      r0,[r2,#0x10]
        LDR      r0,[r2,#0x10]
        ORR      r0,r0,#0x40
        STR      r0,[r2,#0x10]
|L1.472|
        LDR      r0,[r2,#0xc]
        LSLS     r0,r0,#31
        BNE      |L1.472|
|L1.478|
        MOVS     r0,#0
        POP      {pc}
        ENDP

Flash_Pagedata_Write PROC
        PUSH     {r4-r8,lr}
        MOV      r8,r0
        LDR      r7,[sp,#0x18]
        MOV      r6,r1
        MOV      r4,r2
        MOV      r5,r3
        MOV      r0,r4
        BL       Flash_Page_Erase
        CBZ      r0,|L1.530|
        MOVS     r0,#1
|L1.506|
        POP      {r4-r8,pc}
|L1.510|
        MOV      r0,r4
        LDRH     r1,[r8],#2
        ADDS     r4,r4,#2
        BL       Flash_Halfword_Program
        CMP      r0,#1
        BEQ      |L1.536|
        SUBS     r5,r5,#1
        UXTH     r5,r5
|L1.530|
        CMP      r5,#0
        BNE      |L1.510|
        B        |L1.560|
|L1.536|
        MOVS     r0,#1
        B        |L1.506|
|L1.540|
        MOV      r0,r4
        LDRB     r1,[r6],#1
        ADDS     r4,r4,#2
        BL       Flash_Halfword_Program
        CMP      r0,#1
        BEQ      |L1.586|
        SUBS     r7,r7,#1
        UXTH     r7,r7
|L1.560|
        CMP      r7,#0
        BNE      |L1.540|
        MOV      r1,#0x453
        MOV      r0,r4
        BL       Flash_Halfword_Program
        CMP      r0,#1
        BEQ      |L1.590|
        BL       Flash_FPEC_Lock
        MOVS     r0,#0
        B        |L1.506|
|L1.586|
        MOVS     r0,#1
        B        |L1.506|
|L1.590|
        MOVS     r0,#1
        B        |L1.506|
        ENDP

        DCW      0x0000
|L1.596|
        DCD      0x40021000
|L1.600|
        DCD      0x40022000
|L1.604|
        DCD      0x45670123
|L1.608|
        DCD      0xcdef89ab
|L1.612|
        DCD      0xe0000800

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT Flash_Init [CODE]
        EXPORT Flash_FPEC_Unlock [CODE]
        EXPORT Flash_FPEC_Lock [CODE]
        EXPORT Flash_OPT_Unlock [CODE]
        EXPORT Flash_OPT_Lock [CODE]
        EXPORT Flash_Halfword_Program [CODE]
        EXPORT Flash_Page_Erase [CODE]
        EXPORT Flash_Mass_Erase [CODE]
        EXPORT Flash_OPTBYTE_Program [CODE]
        EXPORT Flash_OPTBYTE_Erase [CODE]
        EXPORT Flash_Pagedata_Write [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
