; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\system_stm32f10x.o --depend=..\Output\system_stm32f10x.d --cpu=Cortex-M3 --apcs=interwork -O1 -I.\src -I.\inc -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_CL --omf_browse=..\Output\system_stm32f10x.crf ..\CMSIS\system_stm32f10x.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

SetSysClockTo72 PROC
        MOVS     r0,#0
        LDR      r1,|L1.404|
        LDR      r2,[r1,#0]
        ORR      r2,r2,#0x10000
        STR      r2,[r1,#0]
        MOV      r3,#0x500
|L1.16|
        LDR      r2,[r1,#0]
        AND      r2,r2,#0x20000
        ADDS     r0,r0,#1
        CBNZ     r2,|L1.30|
        CMP      r0,r3
        BNE      |L1.16|
|L1.30|
        LDR      r0,[r1,#0]
        LSLS     r0,r0,#14
        BPL      |L1.40|
        MOVS     r0,#1
        B        |L1.42|
|L1.40|
        MOVS     r0,#0
|L1.42|
        CMP      r0,#1
        BNE      |L1.174|
        LDR      r0,|L1.408|
        LDR      r2,[r0,#0]
        ORR      r2,r2,#0x10
        STR      r2,[r0,#0]
        LDR      r2,[r0,#0]
        BIC      r2,r2,#3
        STR      r2,[r0,#0]
        LDR      r2,[r0,#0]
        ORR      r2,r2,#2
        STR      r2,[r0,#0]
        LDR      r0,[r1,#4]
        STR      r0,[r1,#4]
        LDR      r0,[r1,#4]
        STR      r0,[r1,#4]
        LDR      r0,[r1,#4]
        ORR      r0,r0,#0x400
        STR      r0,[r1,#4]
        LDR      r0,[r1,#0x2c]
        LDR      r2,|L1.412|
        ANDS     r0,r0,r2
        STR      r0,[r1,#0x2c]
        LDR      r0,[r1,#0x2c]
        LDR      r2,|L1.416|
        ORRS     r0,r0,r2
        STR      r0,[r1,#0x2c]
        LDR      r0,[r1,#0]
        ORR      r0,r0,#0x4000000
        STR      r0,[r1,#0]
|L1.112|
        LDR      r0,[r1,#0]
        LSLS     r0,r0,#4
        BPL      |L1.112|
        LDR      r0,[r1,#4]
        BIC      r0,r0,#0x3f0000
        STR      r0,[r1,#4]
        LDR      r0,[r1,#4]
        ORR      r0,r0,#0x1d0000
        STR      r0,[r1,#4]
        LDR      r0,[r1,#0]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0]
|L1.142|
        LDR      r0,[r1,#0]
        LSLS     r0,r0,#6
        BPL      |L1.142|
        LDR      r0,[r1,#4]
        BIC      r0,r0,#3
        STR      r0,[r1,#4]
        LDR      r0,[r1,#4]
        ORR      r0,r0,#2
        STR      r0,[r1,#4]
|L1.164|
        LDR      r0,[r1,#4]
        UBFX     r0,r0,#2,#2
        CMP      r0,#2
        BNE      |L1.164|
|L1.174|
        BX       lr
        ENDP

SetSysClock PROC
        B        SetSysClockTo72
        ENDP

SystemInit PROC
        PUSH     {r4,lr}
        LDR      r0,|L1.404|
        LDR      r1,[r0,#0]
        ORR      r1,r1,#1
        STR      r1,[r0,#0]
        LDR      r1,[r0,#4]
        LDR      r2,|L1.420|
        ANDS     r1,r1,r2
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0]
        LDR      r2,|L1.424|
        ANDS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,[r0,#0]
        BIC      r1,r1,#0x40000
        STR      r1,[r0,#0]
        LDR      r1,[r0,#4]
        BIC      r1,r1,#0x7f0000
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0]
        BIC      r1,r1,#0x14000000
        STR      r1,[r0,#0]
        MOV      r1,#0xff0000
        STR      r1,[r0,#8]
        MOVS     r1,#0
        STR      r1,[r0,#0x2c]
        BL       SetSysClock
        LDR      r1,|L1.428|
        MOV      r0,#0x8000000
        STR      r0,[r1,#0]
        POP      {r4,pc}
        ENDP

SystemCoreClockUpdate PROC
        PUSH     {r4-r6,lr}
        LDR      r3,|L1.404|
        LDR      r0,[r3,#4]
        AND      r0,r0,#0xc
        LDR      r2,|L1.432|
        LDR      r1,|L1.436|
        CBZ      r0,|L1.302|
        LDR      r4,|L1.440|
        CMP      r0,#4
        BEQ      |L1.306|
        CMP      r0,#8
        BEQ      |L1.310|
        STR      r2,[r1,#0]  ; SystemCoreClock
|L1.282|
        LDR      r0,[r3,#4]
        LDR      r2,|L1.436|
        UBFX     r0,r0,#4,#4
        ADDS     r2,r2,#4
        LDRB     r0,[r2,r0]
        LDR      r2,[r1,#0]  ; SystemCoreClock
        LSRS     r2,r2,r0
        STR      r2,[r1,#0]  ; SystemCoreClock
        POP      {r4-r6,pc}
|L1.302|
        STR      r2,[r1,#0]  ; SystemCoreClock
        B        |L1.282|
|L1.306|
        STR      r4,[r1,#0]  ; SystemCoreClock
        B        |L1.282|
|L1.310|
        LDR      r0,[r3,#4]
        AND      r0,r0,#0x3c0000
        LDR      r2,[r3,#4]
        AND      r2,r2,#0x10000
        LSRS     r0,r0,#18
        CMP      r0,#0xd
        BEQ      |L1.332|
        ADDS     r0,r0,#2
        B        |L1.334|
|L1.332|
        MOVS     r0,#6
|L1.334|
        CBZ      r2,|L1.384|
        LDR      r2,[r3,#0x2c]
        AND      r5,r2,#0x10000
        LDR      r2,[r3,#0x2c]
        AND      r2,r2,#0xf
        ADDS     r2,r2,#1
        CBZ      r5,|L1.392|
        LDR      r5,[r3,#0x2c]
        UBFX     r6,r5,#4,#4
        ADDS     r6,r6,#1
        LDR      r5,[r3,#0x2c]
        UBFX     r5,r5,#8,#4
        ADDS     r5,r5,#2
        UDIV     r4,r4,r6
        MULS     r4,r5,r4
        UDIV     r2,r4,r2
        MULS     r2,r0,r2
        STR      r2,[r1,#0]  ; SystemCoreClock
        B        |L1.282|
|L1.384|
        LDR      r2,|L1.444|
        MULS     r0,r2,r0
        STR      r0,[r1,#0]  ; SystemCoreClock
        B        |L1.282|
|L1.392|
        UDIV     r2,r4,r2
        MULS     r2,r0,r2
        STR      r2,[r1,#0]  ; SystemCoreClock
        B        |L1.282|
        ENDP

        DCW      0x0000
|L1.404|
        DCD      0x40021000
|L1.408|
        DCD      0x40022000
|L1.412|
        DCD      0xfffef000
|L1.416|
        DCD      0x00010644
|L1.420|
        DCD      0xf0ff0000
|L1.424|
        DCD      0xfef6ffff
|L1.428|
        DCD      0xe000ed08
|L1.432|
        DCD      0x007a1200
|L1.436|
        DCD      ||.data||
|L1.440|
        DCD      0x017d7840
|L1.444|
        DCD      0x003d0900

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

SystemCoreClock
        DCD      0x044aa200
AHBPrescTable
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x01,0x02,0x03,0x04
        DCB      0x06,0x07,0x08,0x09

        EXPORT SystemInit [CODE]
        EXPORT SystemCoreClockUpdate [CODE]
        EXPORT SystemCoreClock [DATA,SIZE=4]
        EXPORT AHBPrescTable [DATA,SIZE=16]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP SetSysClockTo72
        KEEP SetSysClock

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
