//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZLG522S DLL Test.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ZLG522SDLLTEST_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MIFARE               130
#define IDD_DIALOG_SET_WORK_MODE        131
#define IDD_DIALOG_ISO14443             132
#define IDD_DIALOG_PLUSCPU              133
#define IDD_DIALOG_AUTO_RES             134
#define IDC_COMBO_MODULE_TYPE           1001
#define IDC_COMBO_COMNO                 1002
#define IDC_COMBO_BAUD_RATE             1003
#define IDC_BUTTON_OPEN                 1004
#define IDC_BUTTON_GET_DEV_INFO         1006
#define IDC_BUTTON_RE                   1007
#define IDC_COMBO1                      1018
#define IDC_COMBO_BAUD_RATE_NO          1018
#define IDC_COMBO_AUTH_KEY_SECTOR       1018
#define IDC_COMBO_AUTO_KEY_SECTOR       1019
#define IDC_COMBO2                      1020
#define IDC_COMBO_COMM_MODE             1020
#define IDC_COMBO_AUTH_SECTOR           1020
#define IDC_EDIT1                       1021
#define IDC_EDIT_DEV_INFO               1021
#define IDC_EDIT_MODULE_ADR             1021
#define IDC_EDIT_SEND                   1021
#define IDC_EDIT_TX                     1021
#define IDC_EDIT2                       1022
#define IDC_EDIT_REV                    1022
#define IDC_EDIT_BLOCK1                 1022
#define IDC_STATIC_CMD_TYPE             1023
#define IDC_EDIT_PAUSE_TIME             1023
#define IDC_STATIC_CMD                  1024
#define IDC_STATIC_CMD_INFO             1025
#define IDC_STATIC_CMD_RES              1027
#define IDC_EDIT4                       1028
#define IDC_TAB_MODULE_TYPE             1030
#define IDC_TAB_CARD_MODE               1030
#define IDC_BUTTON_CFG_PCD              1031
#define IDC_BUTTON_CLOSE_PCD            1032
#define IDC_BUTTON_READ_REG             1034
#define IDC_BUTTON_WRATE_REG            1035
#define IDC_EDIT_WAIT_TIME              1036
#define IDC_RADIO2                      1038
#define IDC_RADIO3                      1039
#define IDC_RADIO4                      1040
#define IDC_BUTTON_SET_MODULE_WORK_MODE 1044
#define IDC_BUTTON_CARD_RESET           1045
#define IDC_EDIT_REG_ADR                1046
#define IDC_EDIT_REG_VAL                1047
#define IDC_RADIO_TX_MODE               1048
#define IDC_CHECK_CHANGE_WORK_MODE      1049
#define IDC_CHECK_CHANGE_BAUD_RATE      1050
#define IDC_CHECK_CHANGE_MODULE_ADR     1051
#define IDC_CHECK_CHANGE_AUTO_DETECT    1052
#define IDC_COMBO_WORK_MODE             1073
#define IDC_COMBO_TXMODE                1075
#define IDC_COMBO_REQ_MODE              1076
#define IDC_COMBO_AUTH_MODE             1077
#define IDC_COMBO_SECTOR                1078
#define IDC_COMBO_BNR                   1079
#define IDC_COMBO_EXT                   1080
#define IDC_RADIO_CRYPTO1               1081
#define IDC_RADIO_AES                   1082
#define IDC_EDIT_KEY                    1083
#define IDC_BUTTON_REQUEST              1084
#define IDC_BUTTON_AUTI                 1085
#define IDC_BUTTON_SELECT               1086
#define IDC_EDIT5                       1087
#define IDC_BUTTON_AUTH                 1088
#define IDC_COMBO3                      1089
#define IDC_COMBO_KEY_TYPE              1089
#define IDC_BUTTON10                    1090
#define IDC_EDIT6                       1091
#define IDC_EDIT7                       1092
#define IDC_EDIT8                       1093
#define IDC_EDIT10                      1094
#define IDC_EDIT11                      1095
#define IDC_EDIT12                      1096
#define IDC_CHECK_                      1098
#define IDC_CHECK6                      1099
#define IDC_CHECK7                      1100
#define IDC_CHECK8                      1101
#define IDC_CHECK_2                     1101
#define IDC_CHECK9                      1102
#define IDC_CHECK10                     1103
#define IDC_CHECK11                     1104
#define IDC_BUTTON_READ                 1105
#define IDC_BUTTON_WRITE                1106
#define IDC_COMBO4                      1107
#define IDC_BUTTON13                    1108
#define IDC_BUTTON14                    1109
#define IDC_BUTTON15                    1110
#define IDC_EDIT9                       1111
#define IDC_COMBO5                      1113
#define IDC_BUTTON16                    1114
#define IDC_BUTTON17                    1115
#define IDC_BUTTON18                    1116
#define IDC_BUTTON19                    1117
#define IDC_CHECK1                      1118
#define IDC_RADIO1                      1119
#define IDC_COMBO6                      1120
#define IDC_BUTTON1                     1121
#define IDC_BUTTON_RATS                 1121
#define IDC_BUTTON_GET_AUTO_RES         1121
#define IDC_BUTTON2                     1122
#define IDC_BUTTON_SEND                 1122
#define IDC_BUTTON_READ_RES             1122
#define IDC_BUTTON_ACTI                 1123
#define IDC_COMBO_REQ_CODE              1124
#define IDC_BUTTON_DESELECT             1127
#define IDC_EDIT_CARD_INFO              1128
#define IDC_EDIT_ATS                    1129
#define IDC_LIST1                       1130
#define IDC_EDIT_ATQ                    1131
#define IDC_EDIT_UID                    1132
#define IDC_EDIT_SAK                    1133
#define IDC_COMBO_AUTO_REQ_CODE         1134
#define IDC_COMBO_AUTO_TXMODE           1135
#define IDC_COMBO_AUTO_AUTH_MODE        1136
#define IDC_CHECK_AUTO_SEND             1137
#define IDC_CHECK_AUTO_INIT             1138
#define IDC_CHECK_AUTO_CONT             1139
#define IDC_CHECK_AUTO_HALT             1140
#define IDC_COMBO_AUTO_SECTOR           1141
#define IDC_COMBO_AUTO_BNR              1142
#define IDC_COMBO_AUTO_EXT              1143
#define IDC_COMBO_BLOCK                 1144
#define IDC_COMBO_SBLOCK                1145
#define IDC_COMBO_DBLOCK                1146
#define IDC_BUTTON_ANTI                 1147
#define IDC_EDIT_AUTO_KEY               1148
#define IDC_RADIO_AUTO_CRYPTO1          1149
#define IDC_RADIO_AUTO_AES              1150
#define IDC_EDIT_AUTH_KEY               1151
#define IDC_EDIT_DATA                   1152
#define IDC_EDIT_VAL                    1153
#define IDC_BUTTON_READ_VAL             1154
#define IDC_BUTTON_WRITE_VAL            1155
#define IDC_BUTTON_INC_VAL              1156
#define IDC_BUTTON_DEC_                 1157
#define IDC_BUTTON_RES                  1158
#define IDC_BUTTON_AUTO_SET_PARA        1159
#define IDC_EDIT_BLOCK2                 1161
#define IDC_RADIO5                      1162
#define IDC_RADIO_CNT                   1163
#define IDC_EDIT_BLOCK3                 1164
#define IDC_EDIT_TIME_OVER              1165

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1166
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
