; generated by ARM C/C++ Compiler, 4.1 [Build 894]
; commandline ArmCC [--debug -c --asm -o..\Output\test.o --depend=..\Output\test.d --cpu=Cortex-M3 --apcs=interwork -O0 -I.\inc -I.\src -I..\CMSIS -I"E:\Keil 4 ARM\ARM\RV31\Inc" -I"E:\Keil 4 ARM\ARM\CMSIS\Include" -I"E:\Keil 4 ARM\ARM\Inc\ST\STM32F10x" -DSTM32F10X_MD --omf_browse=..\Output\test.crf src\test.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

WWDG_IRQHandler PROC
        ADDS     r1,r0,#1
        UXTB     r0,r1
        BX       lr
        ENDP

||fun|| PROC
        ADDS     r0,r1,#1
        MOV      r1,r0
        BX       lr
        ENDP

main PROC
        PUSH     {r4,lr}
        LDR      r0,|L1.48|
        LDRH     r4,[r0,#2]  ; buff
        MOVS     r0,#0xc
        LDR      r1,|L1.52|
        STRH     r0,[r1,#2]
        MOVS     r0,#0xd
        LDR      r1,|L1.56|
        STRH     r0,[r1,#1]
        MOV      r2,pc
        AND      r2,r2,#3
        MOV      r3,pc
        BL       ||fun||
        MOVS     r0,#0x36
        POP      {r4,pc}
        ENDP

|L1.48|
        DCD      buff
|L1.52|
        DCD      ms0
|L1.56|
        DCD      ms1

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=0

buff
        DCB      0x00,0x01,0x02,0x03
ms0
        DCDU     0x00000000
ms1
        DCB      0x00,0x00,0x00

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT WWDG_IRQHandler [CODE]
        EXPORT ||fun|| [CODE]
        EXPORT main [CODE]
        EXPORT ms0 [DATA,SIZE=4]
        EXPORT ms1 [DATA,SIZE=3]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP buff

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
